### ISSUE TITLE
Actualizar el tag de Google Analytics en BioModelos

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-website#336]
Google hizo el lanzamiento de una nueva versión de Google Analytics que involucra un nuevo tag (gtag.js) respecto al que se venía utilizando anteriormente (analytics.js). Este tag tendrá soporte de futuras actualizaciones y también permitirá tener acceso a nuevas métricas y opciones de GA. 

Para este proceso se debe tener en cuenta que debido al uso de Turbolinks en Rails, es necesario hacer un proceso adicional para que cada página cargada se rea reconocida. A continuación documentación sobre el nuevo tag:

[Google Analytics 4](https://support.google.com/analytics/answer/9304153?hl=es&ref_topic=9303319)
[Rails 6 con Google Analytics](https://levelup.gitconnected.com/ruby-on-rails-6-with-google-analytics-turbolinks-and-a-content-security-policy-c4e078df8530)

Consideraciones:
Ya existe una cuenta de GA para BioModelos.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/336?planning-poker) with ZenHub @alegnaaived @danflop @Trjegul84

**Comment by erikasv** [comment]
En PR conectado se solicitó un cambio pequeño que será abordado en el siguiente sprint
