### ISSUE TITLE
Revisar estrategia para actualización del recaptcha

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-website#342]
Previamente se hizo una revisión sobre las posibles alternativas para actualizar la versión del recaptcha que se tiene actualmente en BioModelos, los comentarios correspondientes están en la tarea [#86](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biomodelos-scrum/86)

**Comment by alegnaaived** [comment]
[Enlace a la tarea cerrada #86](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biomodelos-scrum/86)

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/342?planning-poker) with ZenHub @alegnaaived @danflop @erikasv @Trjegul84
