### ISSUE TITLE
Verificar requerimientos para la implementación de certificado SSL en BioModelos

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-website#345]
Para poder implementar un certificado SSL en BioModelos es necesario verificar las configuraciones y requerimientos necesarios para la aplicación de Rails versión 6. Para esto se puede tener en cuenta la documentación oficial y algunas guías como esta: [https://www.pluralsight.com/guides/using-https-with-ruby-on-rails](https://www.pluralsight.com/guides/using-https-with-ruby-on-rails)

## Resultado
El objetivo final de la tarea es tener un listado de los requerimientos que necesitan ser ajustados para crear nuevas tareas que permitan su implementación.

**Comment by erikasv** [comment]
De acuerdo a la guía enlazada (y no encontré nada diferente en otras guías) en realidad lo único que hay que hacer para que la aplicación funcione con https es habilitarlo en la configuración, la cual puede ser con `force_ssl` o `rack-ssl`. De resto todo está en el servidor web, que en nuestro caso creo que sería un nginx (el institucional).

Entre las recomendaciones adicionales deberíamos hacer los siguientes ajustes:
-  No se deberían utilizar url absolutas al sitio mismo y hay muchas!
- Evitar contenido mixto (sección `Load Third-party Assets via HTTPS Whenever Possible` de la guía)
    - Aactualmente se consumen recursos por http de los siguientes sitios, los cuales tienen una versión en https: openstreetmaps, sibcolombia, fondoadaptacion, calidris, asoprimatologicacolombiana, acherpetologia, nhm.ac.uk, butterfly-int, geobon, 
    - Los siguientes sitios no tienen una versión en https: el geoserver institucional, el sitio del instituto y el repositorio del instituto.
    - Los enlaces al sitio mismo de biomodelos se corregirían con el cambio en cuestión.
    - Hay algunos enlaces en http que redirigen a https, otros que no existen, otros que cambiaron, como el del vcongresocolombianodeornitologia y el del sibcolombia
    - No sé si habrían inconvenientes con las peticiones al api y al geoserver, pero creo que no.

> El proceso de actualización de las url es largo, pero más allá de enlaces a otros sitios no identifiqué que se estuvieran cargando imágenes u otro tipo de cosas que pudiesen generar warnings.

No encontré nada relacionado con las acciones a tomar con devise, pero han habido inconvenientes en versiones anteriores de rails, creo que la única forma de saber si habrían inconvenientes es probando.

Según la guía misma y otros recursos que vi se podría crear un ambiente con ssl en la máquina local para hacer las pruebas necesarias, creo que sería bueno darle un intento a esto para prevenir inconvenientes en producción.

**Comment by danflop** [comment]
De acuerdo con las actividades listadas. Incluiría tener en cuenta alternativas para sitios que no tengan versión https.

**Comment by erikasv** [comment]
Con alternativas se refiere a cambiar los enlaces, por ejemplo enlazar al GeoServer de AWS.
