### ISSUE TITLE
Forzar ssl en la aplicación

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-website#346]
## Descripción

De acuerdo a los resultados de la tarea [345](https://github.com/PEM-Humboldt/biomodelos-website/issues/345#issuecomment-1030347919) y la prueba realizada en [#91](https://github.com/PEM-Humboldt/biomodelos-scrum/issues/91) se deben realizar las acciones y verificaciones necesarias para asegurar que la aplicación va a funcionar correctamente.

Tener en cuenta, pero no exclusivamente:
1. Habilitar el forzado de ssl en la aplicación, en la guía referenciada en la tarea [#345](https://github.com/PEM-Humboldt/biomodelos-website/issues/345) hablan de una versión de rails más vieja a la que usamos, verificar y hacer el proceso como se indique para la versión actual que estamos usando.
1. Corregir **TODOS** los enlaces absolutos al sitio por enlaces relativos usando las funciones que rails ofrece para eso (es el primer punto de las actividades listadas de la tarea 345)
1. Actualizar los enlaces que se pueda por enlaces a los sitios https
1. Discutir con @danflop las alternativas a usar para aquellos que no tienen versión https
1. Probar todo lo que se pueda de la aplicación (asegurarse de que se está conectado a las bases de datos de pruebas!)

**Comment by alegnaaived** [comment]
Guía: https://www.matthewhoelter.com/2020/02/19/how-to-setup-force-ssl-on-nginx-and-lets-encrypt.html

**Comment by alegnaaived** [comment]
Se identificó la librería[ Pathname ](https://ruby-doc.org/stdlib-2.4.0/libdoc/pathname/rdoc/Pathname.html)para reducir las URL

**Comment by alegnaaived** [comment]
Los avances en esta tarea están en esta [rama](https://github.com/PEM-Humboldt/biomodelos-website/tree/feature/forceLocalSSL).

La  línea

**Comment by Trjegul84** [comment]
Aunque no he logrado ejecutar el ambiente de biomodelos completo en mi local, busque unas soluciones recomendadas para el problema de forzar todos los enlaces a SSL y encontré que no solo basta con configurar redirect false en el archivo `production.rb`. Tal vez la forma en que se tiene solo redirecciona los enlaces del index pero no no otros entonces como Nginx es sólo un proxy se debe pasar la petición a la aplicación rails, este es el ejemplo que podría servir:

```
location / {
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto https;
  proxy_redirect off;
  proxy_pass http://localhost;
}
```
Otra opción posible es forzar la re dirección de todas las peticiones a https, este es un ejemplo:
```
# Tells the browser to always force SSL. 
# Do not uncomment this line if there is a chance you will turn off SSL
# add_header Strict-Transport-Security "max-age=31536000; includeSubdomains"; 

if ($host != "www.mydomain.com") {
    return 301 https://www.mydomain.com$request_uri;
}
if ($scheme != "https") {
    return 301 https://$host$request_uri;
}
```

**Comment by erikasv** [comment]
Para probar las funcionalidades del sitio forzando el ssl se creó una nueva rama y se tomarn algunos commits de la rama dejara por Angela.

Finalmente se logró poner a funcionar el sitio forzando el ssl (sin desactivar ninguna configuración de parte de rails), pero para que funcione debe llegar un header desde el nginx institucional (ver comentario nuevo de la tarea [91](https://github.com/PEM-Humboldt/biomodelos-scrum/issues/91#issuecomment-1164673237)).

Adicionalmente ya se corrigieron casi todas las url absolutas al sitio mismo (se dejaron 2 en el header de la aplicación y los de las traducciones).

Falta revisar las demás url y una última revisión del comportamiento del sitio.
