### ISSUE TITLE
Cambiar autenticación de smtp

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-website#386]
# Descripción y resultados:

Cambiar la forma en la que se usa el servidor smtp. Ver las tareas de la sala biomodelos-dev donde hay más información en la pestaña de tareas.

# Consideraciones
Se creó también una tarea en la sala de BioModelos para el contexto del error (no hay forma de enlazar el chat, así que toca buscar por el mensaje o la url par leer toda la historia). Favor revisar las dos salas para dar la estimación

# Actualización 16/07

TI ya cambió la configuración de la cuenta para poder habilitar la opción que necesitamos.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/386?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by erikasv** [comment]
Edwin me contestó que va a poner el caso, es probable que esto se demore

**Comment by ManuelStardust** [comment]
Se genero la clave de gmail para apps y se actualizó en la configuración del ambiente de producción de Biomodelos. Se hizó una prueba de envío de correo desde la aplicación y se verifica que aparece en la bandeja de salida en gmail.
