### ISSUE TITLE
Probar capa de invemar

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-website#397]
# Descripción y resultado

Cargar la [capa de invemar](https://drive.google.com/file/d/1qj5UW3dVqHOXHiaqmexd_U9UEfA1EVY0/view?usp=drive_link) al GeoServer y verificar cómo se ve en la aplicación en el ambiente de pruebas.

# Consideraciones

Seguramente es necesario crear una nueva especie o asociarle un modelo a otra, en ese caso hacer esto en el ambiente de prueba.

Las instrucciones de este [documento](https://docs.google.com/document/d/1IgmDrZ1n473VSyEfQci3IFZpmt_MIuIYHovQxSllSlw/edit#heading=h.y36ma8j24fd4) pueden ser de ayuda

**Comment by cazapatamar** [comment]
Se sube la capa al ambiente de pruebas y se envia correo con los resultados a Carlos J y Elkin

<img width="1712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3hvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06c2fd3b22bfb1b8f02235c49339730095ecd6f0/imagen.png" alt="imagen.png" />
