### ISSUE TITLE
Actualizar mensaje en el visor sobre modelos estadísticos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-website#398]
# Descripción y resultado

Actualizar en la plataforma el mensaje que se muestra cuando el modelo que se carga en el visor es un modelo estadístico.

El mensaje está actualizado en el [documento](https://docs.google.com/document/d/1gyE1W149gCMWPaWw19mbU1vbUrzlDHLReu9_jxumwMQ/edit#heading=h.5yj5pndfzcxy) del acuerdo sobre modelos

# Consideraciones
Tocará modificar localmente el estado de algún modelo para visualizar este mensaje, pues actualmente no existen modelos estadísticos

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/398?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se actualiza el mensaje para los modelos estadisticos y ademas se agrega el case para mostrar el nombre del estado ya que este no existia para los estadisticos.
