### ISSUE TITLE
Revisar el tema del HTTP - HTTPS en biomodelos

### ISSUE THREAD

**Issue by hacheG** [PEM-Humboldt/biomodelos-website#403]
Al intentar ingresar a la aplicación de Biomodelos se genera un error que al parecer es debido a que la dirección carga con https, pero sin tener certificados de seguridad la aplicación no carga y se debe usar el modo incógnito para poder ingresar 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ff26c7ccefcfa166c675ae0ca47028d7095c9c2/image.png)

**Comment by hacheG** [comment]
se le pregunto a Daniel Sepulveda sobre este tema y el recomendó generar un certificado autofirmado como solución temporal, ademas sugirió que mirásemos el nginx del api de biomodelos, ya que para esta aplicación se había generado dicho certificado, con ayuda de @ManuelStardust  se hizo la revisión pero no se pudo hallar el nginx para tener un ejemplo de como se hace el procedimiento del certificado.

**Comment by erikasv** [comment]
El tema del certificado autofirmado va a hacer que en los navegadores salga una advertencia de seguridad que haga que las personas tengan que aceptar el riesgo para visitar la página, eso no es una buena idea, es mejor esperar a que se ponga el certificado de seguridad a todo el dominio humboldt.

Yo creo que esto es un problema de caché desde los navegadores de las personas, alguna vez se entregó mal un enlace de biomodelos con el https y desde ahí el navegador quedó intentando entrar por https

**Comment by erikasv** [comment]
@cazapatamar @hacheG por favor revisar si esta tarea es pertinente o la cerramos
