### ISSUE TITLE
Hacer pruebas para PNG de especies marinas

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-website#412]
Se intentó hacer una carga en diciembre de modelos con uso de PNGs pero no fue exitosa porque salian carridos en el mapa.

Los PNGs, thumbs y zip estan [acá](https://drive.google.com/drive/u/1/folders/1HmZovvF8tyqB1OPnI_lq4Gj7VPYQqz_P).

Hacer una prueba con alguna de estas 2 opciones:

1- Creando una especie de prueba y un modelo de prueba (Pasos 1 y 2 de este [documento](https://docs.google.com/document/d/1IgmDrZ1n473VSyEfQci3IFZpmt_MIuIYHovQxSllSlw/edit#heading=h.y36ma8j24fd4))
2- De la carga fallida quedaron creados los modelos en al ambiente de pruebas y tambien se podrian usar para la prueba. Este es el [listado](https://docs.google.com/spreadsheets/d/1XSh05XEuuBRqLHZu_CY60a5pIO4RzO5EgESkPbly1nc/edit#gid=706884505) de taxIDs y modelIDs

Para subir el modelo PNG, thumb y zip seguir el proceso normal de carga por este [flujo](https://docs.google.com/document/d/1K6zB5hn3OiTq7z1F9Qs46BaMjm5HMrjtNgyX0D9Tpl0/edit).

<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVBtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da8fc6801fbcdb318f594e3393e88f3d2fd7099a/imagen.png" alt="imagen.png" />

Tener en cuenta el extent que se tiene en biomodelos para imagenes.

**Resultado:** 
Realizar la revisión en biomodelos, diagnosticar el problema y elaborar un plan de solución.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/412?planning-poker) with Zenhub @erikasv @hacheG @ManuelStardust

**Comment by erikasv** [comment]
El problema se debía a lo que habíamos venido suponiendo. El extent debe ser más grande para los modelos marinos. En los PR que creé está la implementación para tener en cuenta el nuevo campo `extentSize`, todos los modelos marinos deberán tener ese campo en valor `large`, el cual aplicará el extent que me entregó Carlos Jair para los modelos marinos. En la base de datos de prueba ya cambié ese campo para el modelo que se carga por defecto de `Aetobatus narinari`.

@cazapatamar @ManuelStardust Por favor probar con varias especies y modelos.
