### ISSUE TITLE
Revisar recaptcha de biomodelos

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-website#413]
Revisar si hay alguna configuración que se pueda mover, Carlos Jair el año pasado reportó que estbaan llegando muchos correos basura del formulario de contacto

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/413?planning-poker) with Zenhub @erikasv @hacheG @ManuelStardust

**Comment by ManuelStardust** [comment]
No es posible agregar configuraciones adicionales para fortalecer el uso del recaptcha actual ya que es v2, por tanto se recomienda hacer el cambio a recaptcha v3.
