### ISSUE TITLE
Actualizar recaptcha

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-website#415]
# Descripción

Actualizar el recaptcha a la versión 3.

Socializar las configuraciones aplicadas (si hay algunas) o si es necesario, crear un documento en la carpeta de [BioModelos](https://drive.google.com/drive/folders/1_NgcUl7RNJVWKDA5q0Dm_plRSXaARCRU)

**Comment by ManuelStardust** [comment]
Se probo la instalación de las gemas correspondientes a recaptcha v3 sin embargo tengo problemas con la ejecución del sitio en local.

**Comment by erikasv** [comment]
Es posible que esto no sea la solución al problema original: https://datadome.co/guides/captcha/recaptchav2-recaptchav3-efficient-bot-protection/

**Comment by erikasv** [comment]
Igual, para este tema del recaptcha lo mejor sí será mantener las dos versiones como se explica en el ejemplo de la gema.
