### ISSUE TITLE
Problema en edición de modelos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-website#421]
# Descripción

El escenario es el siguiente:

Entrar a editar un modelo, si no hay polígonos de ediciones guardadas, crear uno. Guardar los cambios. Recargar la página, el polígono guardado anteriormente debe verse, pero no es clickeable (está por debajo de la capa del modelo). Si se crea un polígono nuevo, quedará también por debajo de la capa del modelo.

## Cosas a tener en cuenta
(a.k.a. lo que encontré)
1. Nada le está dando un orden a las capas que se cargan, pero aún así en el DOM la imagen del modelo queda despué del svg con clase `leaflet-zoom-animated`, si se mueve para que esté arriba, ya se puede interactuar con los polígonos
2. Toda la lógica está en el archivo `app/assets/javascripts/biovisor.js`

**Comment by ManuelStardust** [comment]
Se determino que lo mejor es ordenar las capas a traves de las funciones de leaflet para asignar capas a un pane y posteriormente asignar un z-index, sin embargo esto no es posible con la versión actual de leaflet (0.7.7).

Se intento hacer la actualización de leaflet a la versión actual 1.9.4, pero no es claro como llamar esta version desde el manifest de Rails para javascript (app/assets/javascripts/application.js). Se hizo una actualzación a la versión 1.3.1, sin embargo esta genera varios errores con el código actual por tanto requiere ajustes. Es de tener en cuenta que también se deben actualizar las librerias leaflet.markercluster, leaflet-draw y Leaflet.Coordinates.

Finalmente se realizó un ajuste provisional sobre la hoja de estilos para asignar un valor de z-index a las capas de los polígonos dibujados (hotfix/2.9.2).
