### ISSUE TITLE
Error con usuarios moderadores al ingresar a un grupo sin especies asociadas

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-website#448]
Se está presentando un error al consultar grupos con usuarios moderadores de grupos que no tienen especies:

1. Iniciar sesión con usuario moderador de algun grupo. Puede ser con el usuario biomodelos ya que es moderador de todos.
2. Entrar a algun grupo donde usuario biomodelos sea moderador y que no tenga especies

Si bien entra a la página del grupo, se queda pensando bastante tiempo hasta que sale error de firefox "Esta página se está relentizando .........". Luego de esperar algunos minutos la página responde y permite navegar por el grupo.

<img width="1813" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNld2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4cb1f3caaa13bd00485f8a8ce0368e4ecfecacd/imagen.png" alt="imagen.png" />

Se debe solucionar el error y manejarlo como hotfix. Se incluye en el alcance de esta tarea realizar el despliegue en producción.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-website/448?planning-poker) with Zenhub @erikasv @ManuelStardust

**Comment by erikasv** [comment]
Le cambié la prioridad porque en reunión de avances Carlos me comentó que la solicitud de asignar moderadores al grupo de limnología colombiana vino de parte de una experta que quiere mover el grupo de nuevo, entonces es probable que reporten este problema la siguiente semana

**Comment by erikasv** [comment]
Encontré que el grupo no se congela solo para los moderadores del grupo, sino para todos los expertos del grupo.
