### ISSUE TITLE
Corrimiento de modelo en costas

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/biomodelos-website#64]
El modelo se corre levemente en las costas cuando se usa el pan tool (manita)

**Comment by danflop** [comment]
Se realiza el cambio de la proyección utilizada por defecto en el mapa de EPSG4326 a EPSG3857. De esta manera, ya no se presenta corrimiento según el desplazamiento, pero se identifica un corrimiento que puede venir desde la fuente.

**Comment by erikasv** [comment]
No han habido reportes relacionados con este issue.
